# Generated by Django 5.1.4 on 2026-07-01 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la classe (ex. « Terminale B »).', max_length=120)),
                ('code', models.CharField(db_index=True, help_text="Code d'invitation communiqué aux élèves pour rejoindre la classe.", max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, help_text='Élèves membres de la classe.', related_name='classes_joined', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Enseignant propriétaire de la classe.', on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du cours.', max_length=200)),
                ('content', models.TextField(help_text='Texte source du cours (extrait PDF ou saisie).')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('text', 'Texte')], default='text', help_text='Origine du contenu : PDF importé ou texte collé.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Propriétaire du cours.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du cours / quiz (saisi ou déduit).', max_length=200)),
                ('source_text', models.TextField(help_text='Texte source utilisé pour la génération (extrait PDF ou saisie).')),
                ('score', models.IntegerField(blank=True, help_text='Score /10 obtenu lors de la dernière tentative (None si pas encore passé).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', help_text='Niveau de difficulté demandé à la génération.', max_length=10)),
                ('num_questions', models.PositiveSmallIntegerField(default=10, help_text='Nombre de questions du quiz (5 à 20).')),
                ('theme', models.CharField(blank=True, default='', help_text='Thème ou chapitre ciblé pour la génération (optionnel).', max_length=200)),
                ('is_published', models.BooleanField(default=False, help_text='Quiz publié par un enseignant, distribuable à une classe.')),
                ('assigned_classes', models.ManyToManyField(blank=True, help_text='Classes auxquelles ce quiz est distribué.', related_name='quizzes', to='quizzes.classroom')),
                ('course', models.ForeignKey(blank=True, help_text='Cours source dont ce quiz est issu (null pour les quiz hérités).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizzes.course')),
                ('user', models.ForeignKey(help_text='Propriétaire du quiz.', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='Position de la question dans le quiz (1 à 10).')),
                ('prompt', models.TextField(help_text='Énoncé de la question.')),
                ('options', models.JSONField(help_text="Liste des 4 options (chaînes). Ex : ['Paris', 'Londres', 'Madrid', 'Berlin']")),
                ('correct_index', models.PositiveSmallIntegerField(help_text='Index (0 à 3) de la bonne réponse dans `options`.')),
                ('qtype', models.CharField(choices=[('mcq', 'QCM'), ('truefalse', 'Vrai / Faux'), ('short', 'Réponse courte')], default='mcq', help_text='Type de question : QCM, Vrai/Faux ou réponse courte.', max_length=12)),
                ('correct_text', models.CharField(blank=True, default='', help_text='Bonne réponse attendue pour une question « réponse courte ».', max_length=300)),
                ('selected_index', models.PositiveSmallIntegerField(blank=True, help_text="Dernier index (0 à 3) choisi par l'utilisateur (None si pas répondu).", null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['index'],
                'unique_together': {('quiz', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='N° de tentative de cet élève sur ce quiz (1, 2, 3…) — libellé « cours-N ».')),
                ('score', models.IntegerField(blank=True, help_text='Score obtenu à cette tentative.', null=True)),
                ('total', models.PositiveSmallIntegerField(default=10, help_text='Nombre de questions de la tentative.')),
                ('question_order', models.JSONField(blank=True, default=list, help_text='Ordre (mélangé) des index de questions pour cette tentative.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Tentative',
                'verbose_name_plural': 'Tentatives',
                'ordering': ['quiz_id', 'number'],
                'unique_together': {('quiz', 'student', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveSmallIntegerField(blank=True, help_text='Index choisi (QCM / Vrai-Faux).', null=True)),
                ('text_answer', models.CharField(blank=True, default='', help_text='Réponse saisie (réponse courte).', max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
